# Generated by Django 2.2.5 on 2019-11-12 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_wod'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Wod',
        ),
    ]
