# Generated by Django 2.2.5 on 2019-11-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20191112_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='time',
        ),
        migrations.AddField(
            model_name='workout',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
