# Generated by Django 2.2.5 on 2019-11-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_auto_20191112_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
