# Generated by Django 2.2.5 on 2019-11-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_auto_20191112_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='time',
            field=models.DurationField(null=True),
        ),
    ]
