# Generated by Django 2.2.5 on 2019-09-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='content',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='title',
        ),
        migrations.AddField(
            model_name='schedule',
            name='availability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='eventType',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schedule',
            name='instructor',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
