# Generated by Django 2.2.5 on 2019-10-05 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20191005_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
