# Generated by Django 2.2.5 on 2019-10-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20191023_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='Schedule',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='user',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
