# Generated by Django 2.2.5 on 2019-10-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20191023_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='schedule_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
